[versions]
agp = "8.7.3"
appauth = "1"
appauthVersion = "0.11.1"
design = "28.0.0"
firebaseBom = "33.10.0"
glide = "4.13.2"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.0"
constraintlayout = "2.2.0"
materialVersion = "1.6.1"
playServicesAuth = "21.3.0"
preference = "1.2.1"
preferenceKtx = "1.2.1"
roomRuntime = "2.6.1"
roomCommonJvm = "2.7.0-alpha13"
ucrop = "2.2.10"
recyclerview = "1.4.0"

[libraries]
appauth = { module = "net.openid:appauth", version.ref = "appauth" }
appauth-v0111 = { module = "net.openid:appauth", version.ref = "appauthVersion" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
design = { module = "com.android.support:design", version.ref = "design" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v161 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }
ucrop = { module = "com.github.yalantis:ucrop", version.ref = "ucrop" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

